### ISSUE TITLE
02-filter.py fails by unknown reason:

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#271]
```
python3 ./02-filter-and-move.py --dir target/01
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./02-filter-and-move.py", line 103, in worker
    class_type = get_class_type(filename)
  File "./02-filter-and-move.py", line 64, in get_class_type
    text = f.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 4: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./02-filter-and-move.py", line 125, in <module>
    results = walk_in_parallel()
  File "./02-filter-and-move.py", line 117, in walk_in_parallel
    results = pool.map(worker, fn_gen)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 4: invalid start byte
Makefile:24: recipe for target 'filter' failed
make: *** [filter] Error 1
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
it's because we have path in Chinese: target/01/DuGuQiuBai/Java/day05/code/01_方法重载/MethodDemo.java

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#271` is not assigned, can't get performer
