### ISSUE TITLE
Aibolit train failed

### ISSUE THREAD

**Issue by angusev** [yegor256/aibolit#292]
`>> aibolit train --java_folder ./java_folder`
```Traceback (most recent call last):
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/bin/aibolit", line 11, in <module>
    sys.exit(main())
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/lib/python3.7/site-packages/aibolit/__main__.py", line 384, in main
    run_parse_args(commands)
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/lib/python3.7/site-packages/aibolit/__main__.py", line 89, in run_parse_args
    commands_dict[args.command]()
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/lib/python3.7/site-packages/aibolit/__main__.py", line 380, in <lambda>
    'train': lambda: train(),
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/lib/python3.7/site-packages/aibolit/__main__.py", line 103, in train
    collect_dataset(args.java_folder)
  File "/Users/andrey/Documents/Hometasks/aibolit/wp/aibolit/lib/python3.7/site-packages/aibolit/ml_pipeline/ml_pipeline.py", line 19, in collect_dataset
    os.chdir(Path(Config.home_aibolit_folder(), 'scripts'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/aibolit/scripts'

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
you need to set up env path

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#292` is not assigned, can't get performer
