### ISSUE TITLE
Bug with training dataset

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#331]
Number of features:  42
Traceback (most recent call last):
  File "/opt/conda/bin/aibolit", line 11, in <module>
    load_entry_point('aibolit', 'console_scripts', 'aibolit')()
  File "/home/jovyan/aibolit/aibolit/__main__.py", line 402, in main
    run_parse_args(commands)
  File "/home/jovyan/aibolit/aibolit/__main__.py", line 89, in run_parse_args
    commands_dict[args.command]()
  File "/home/jovyan/aibolit/aibolit/__main__.py", line 398, in <lambda>
    'train': lambda: train(),
  File "/home/jovyan/aibolit/aibolit/__main__.py", line 117, in train
    train_process()
  File "/home/jovyan/aibolit/aibolit/ml_pipeline/ml_pipeline.py", line 103, in train_process
    dataset.preprocess_file()
  File "/home/jovyan/aibolit/aibolit/model/model.py", line 56, in preprocess_file
    self.target /= df['M2'].values.reshape(-1)
TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#331` is not assigned, can't get performer
