### ISSUE TITLE
"Exception: Unknown format" for valid Java code

### ISSUE THREAD

**Issue by g4s8** [yegor256/aibolit#455]
I run the command:
```bash
aibolit recommend --folder src/main/java --format=text --full
```
Against https://github.com/artipie/maven-adapter/ project, but Aibolit fails with error:
```
Traceback (most recent call last):
  File "/home/g4s8/.local/lib64/python3.6/site-packages/aibolit/__main__.py", line 611, in main
    exit_code = run_parse_args(commands)
  File "/home/g4s8/.local/lib64/python3.6/site-packages/aibolit/__main__.py", line 99, in run_parse_args
    return commands_dict[args.command]()
  File "/home/g4s8/.local/lib64/python3.6/site-packages/aibolit/__main__.py", line 608, in <lambda>
    'recommend': lambda: check(),
  File "/home/g4s8/.local/lib64/python3.6/site-packages/aibolit/__main__.py", line 506, in check
    raise Exception('Unknown format')
Exception: Unknown format
```

Version is `aibolit 1.1.2`

To reproduce you can use this commit: https://github.com/artipie/maven-adapter/commit/2135c25f7a4e17dae7f976a3c845047aba8424c3

```bash
git clone https://github.com/artipie/maven-adapter.git
cd maven-adapter
git checkout 2135c25f7a4e17dae7f976a3c845047aba8424c3
aibolit recommend --folder src/main/java --format=text --full
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
`--format=text`  - there is no such a format

format=compact
format=long
format=xml

**Comment by lyriccoder** [comment]
No issue here, close

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#455` is not assigned, can't get performer
