### ISSUE TITLE
If we have ncss = 0, we should ignore file

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#461]
```
$ aibolit check --folder miaosha --format=short --exclude=**/*Test*.java --exclude=D:\temp\chosen_repos\qiurunze123\miaosha
Version 1.1.2 is available, but you are using 0.0.0
d:\git\aibolit\aibolit\model\model.py:189: RuntimeWarning: invalid value encountered in true_divide
  snippet = patterns_orig / ncss
Traceback (most recent call last):
  File "d:\git\aibolit\aibolit\__main__.py", line 653, in main
    exit_code = run_parse_args(commands)
  File "d:\git\aibolit\aibolit\__main__.py", line 99, in run_parse_args
    return commands_dict[args.command]()
  File "d:\git\aibolit\aibolit\__main__.py", line 649, in <lambda>
    'check': lambda: check(),
  File "d:\git\aibolit\aibolit\__main__.py", line 534, in check
    results = list(run_thread(files, args))
  File "d:\git\aibolit\aibolit\__main__.py", line 627, in run_thread
    yield future.result()
  File "C:\Python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\git\aibolit\aibolit\__main__.py", line 245, in run_recommend_for_file
    results_list = inference(input_params, code_lines_dict, args)
  File "d:\git\aibolit\aibolit\__main__.py", line 208, in inference
    sorted_result, importances = predict(input_params, model, args)
  File "d:\git\aibolit\aibolit\__main__.py", line 72, in predict
    preds, importances = model.informative(input, th=th)
  File "d:\git\aibolit\aibolit\model\model.py", line 202, in informative
    temp_arr[i] = temp_arr[i] - (1 / ncss)
ZeroDivisionError: division by zero
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
[RedissonAutoConfiguration.zip](https://github.com/yegor256/aibolit/files/4845937/RedissonAutoConfiguration.zip)

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#461` is not assigned, can't get performer
