### ISSUE TITLE
pip install does not install dependencies

### ISSUE THREAD

**Issue by victornoel** [yegor256/aibolit#80]
I instaledl aibolit with
```
$ pip install --user aibolit
Collecting aibolit
  Downloading https://files.pythonhosted.org/packages/ab/90/0f9885ad2c3fa0e22a173fdbbdf70391caf759fdd1a215b48cc7f1ec04d0/aibolit-0.0.4-py2.py3-none-any.whl
Installing collected packages: aibolit
Successfully installed aibolit-0.0.4
```

And then I tried to run it:
```
$ aibolit processor/src/main/java
Traceback (most recent call last):
  File "/home/victor/.local/bin/aibolit", line 5, in <module>
    from aibolit.__main__ import main
  File "/home/victor/.local/lib/python3.8/site-packages/aibolit/__main__.py", line 31, in <module>
    from aibolit.patterns.nested_blocks.nested_blocks import NestedBlocks, BlockType
  File "/home/victor/.local/lib/python3.8/site-packages/aibolit/patterns/nested_blocks/nested_blocks.py", line 23, in <module>
    import javalang
ModuleNotFoundError: No module named 'javalang'
```

Apparently some dependencies must be missing... the `setup.py` should be referencing them so that `pip install` can install them.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`

**Comment by yegor256** [comment]
@victornoel should be OK now

**Comment by victornoel** [comment]
@yegor256 now it install dev dependencies too, it shouldn't be the case.
